# Generated by Django 6.0.2 on 2026-02-23 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('package_offered', models.CharField(blank=True, max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('hr_name', models.CharField(blank=True, max_length=255)),
                ('hr_contact', models.CharField(blank=True, max_length=255)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('round_type', models.CharField(choices=[('screening', 'Screening'), ('technical', 'Technical'), ('hr', 'HR'), ('final', 'Final'), ('offer', 'Offer')], default='screening', max_length=20)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=10)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('on_site', 'On Site'), ('phone', 'Phone Call'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('result', models.CharField(choices=[('waiting', 'Waiting'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='waiting', max_length=20)),
                ('prep_notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
